# Generated by Django 2.0.5 on 2018-05-13 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tifert', '0002_auto_20180512_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='DATE')),
                ('objet', models.CharField(choices=[('Vap', 'Vapeur'), ('Reclamtion', 'Reclamtion'), ('Transfert', 'Transfert')], max_length=10)),
                ('text', models.CharField(max_length=10)),
                ('fax', models.FileField(upload_to='fax/%Y/%m/%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fax',
                'ordering': ['-date'],
            },
        ),
    ]
