# Generated by Django 2.0.5 on 2018-05-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tifert', '0003_fax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fax',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
