# Generated by Django 2.0.5 on 2018-05-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tifert', '0004_auto_20180513_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.FileField(upload_to='images/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
        migrations.AlterField(
            model_name='defaut_tabia',
            name='doc',
            field=models.FileField(upload_to='Documents/tabia/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='fax',
            name='fax',
            field=models.FileField(upload_to='Documents/fax/%Y/%m/%d/'),
        ),
    ]
