# Generated by Django 2.0.5 on 2018-05-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tifert', '0006_auto_20180513_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='Documents/images/%Y/%m/%d/'),
        ),
    ]
