# Generated by Django 2.0.5 on 2018-05-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tifert', '0007_auto_20180513_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
    ]
