# Generated by Django 2.0.5 on 2018-06-01 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tifert', '0008_auto_20180514_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Photo',
        ),
    ]
